language: clojure

jdk:
  - oraclejdk8

notifications:
  email:
    on_success: never
    on_failure: never

script:
  - lein repl
  - (use 'graftertransformations.querytest)
  - (def triples (create-triple-store))
  - (.isEmpty (.getConnection triples))
  - (insert-triples triples (java.io.File. "output/celica-data.rdf"))
  - (query-result-set triples (with-common-ns-prefixes (from-file "no-limit")))
  - (clear-store triples)

after_script:
  - bash -ex test/coveralls.sh
