language: clojure

jdk:
  - oraclejdk8

notifications:
  email:
    on_success: never
    on_failure: never

script:
  - lein repl < test/query-commands-test.txt

after_script:
  - bash -ex test/coveralls.sh
